// Auto-generated by pac code init + pac code add-data-source
// Do NOT edit .power/schemas/appschemas/dataSourcesInfo.ts manually
import { dataSourcesInfo as generated } from ".power/schemas/appschemas/dataSourcesInfo"

// System tables not added via pac code add-data-source
const systemTables = {
  systemusers: {
    logicalName: "systemuser",
    collectionName: "systemusers",
    primaryIdAttribute: "systemuserid",
    primaryNameAttribute: "fullname",
  },
}

export const dataSourcesInfo = {
  ...generated,
  ...systemTables,
}
