description: Blank Template
entityname: adx_webpage
id: 1dc417d9-1503-47a5-8d7b-d1202f8ff988
isdefault: false
name: Default studio template
type: 756150001
usewebsiteheaderandfooter: true
webtemplateid: a9fcbf7d-114d-485f-920c-b9cd2ef816a7
