annotationid: 194ad739-d1c2-4deb-b30c-04b9baa6fa01
contentdisposition: 756150000
enabletracking: false
excludefromsearch: false
filename: index.html
hiddenfromsitemap: false
id: d07452bf-ee2a-4297-99be-f8f1afba8a7f
isdocument: true
mimetype: text/html
name: index.html
objectid: d07452bf-ee2a-4297-99be-f8f1afba8a7f
objecttypecode: adx_webfile
parentpageid: 7dfee41a-698f-4cae-b790-948e94e4318b
partialurl: index.html
publishingstateid: f19b400a-e073-431a-addd-49304e1ec833
