displayorder: 1
enablerating: false
enabletracking: false
excludefromsearch: false
feedbackpolicy: 756150005
hiddenfromsitemap: false
id: 07ad7f9a-f9c3-4e92-961c-0b0bc9fde274
isroot: false
name: Home
pagetemplateid: 1dc417d9-1503-47a5-8d7b-d1202f8ff988
partialurl: /
publishingstateid: f19b400a-e073-431a-addd-49304e1ec833
rootwebpageid: 7dfee41a-698f-4cae-b790-948e94e4318b
sharedpageconfiguration: false
title: Home
webpagelanguageid: 78dd3082-5d5e-4801-ab0e-ba5336cce037
