displayorder: 2
enablerating: false
enabletracking: false
excludefromsearch: false
feedbackpolicy: 756150000
hiddenfromsitemap: false
id: 492739db-0de2-4b24-b869-ea894e700f37
isroot: true
name: assets
pagetemplateid: a219f25b-1b0a-4f30-8d99-c4169887cecf
parentpageid: 66f96a25-2a12-409a-88f8-08706ae276f3
partialurl: assets
publishingstateid: c717ff14-a8c1-412c-accf-87e29e731d03
sharedpageconfiguration: false
title: assets
