annotationid: 44aba55b-e01b-4866-aa87-2721d1aa6bc7
displayorder: 10
enabletracking: false
excludefromsearch: true
filename: portalbasictheme.css
hiddenfromsitemap: false
id: b65a97ae-596d-4bd2-90dc-7d1edf93536a
isdocument: true
mimetype: text/css
name: portalbasictheme.css
objectid: b65a97ae-596d-4bd2-90dc-7d1edf93536a
objecttypecode: adx_webfile
parentpageid: 7dfee41a-698f-4cae-b790-948e94e4318b
partialurl: portalbasictheme.css
publishingstateid: f19b400a-e073-431a-addd-49304e1ec833
