/**
 * Unified dataSourcesInfo — merges Dataverse tables + Flow connectors.
 * SDK getClient() is a singleton; all data sources must be included in a single info object.
 * .power/schemas/appschemas/dataSourcesInfo.ts is auto-generated by SDK and may be overwritten.
 * Custom entries (systemusers, flow connectors) are added here to survive regeneration.
 */
import { dataSourcesInfo as powerInfo } from "../../.power/schemas/appschemas/dataSourcesInfo";

export const dataSourcesInfo = {
  ...powerInfo,
  systemusers: {
    tableId: "systemuser",
    version: "",
    primaryKey: "systemuserid",
    dataSourceType: "Dataverse",
    apis: {},
  },
  bots: {
    tableId: "bot",
    version: "",
    primaryKey: "botid",
    dataSourceType: "Dataverse",
    apis: {},
  },
  conversationtranscripts: {
    tableId: "conversationtranscript",
    version: "",
    primaryKey: "conversationtranscriptid",
    dataSourceType: "Dataverse",
    apis: {},
  },
  // カスタムインシデントテーブル（pac code add-data-source で追加できない場合の手動追加）
  // PUBLISHER_PREFIX に応じたテーブル名で登録する
  [`${import.meta.env.VITE_PUBLISHER_PREFIX ?? "geek"}_incidents`]: {
    tableId: `${import.meta.env.VITE_PUBLISHER_PREFIX ?? "geek"}_incident`,
    version: "",
    primaryKey: `${import.meta.env.VITE_PUBLISHER_PREFIX ?? "geek"}_incidentid`,
    dataSourceType: "Dataverse",
    apis: {},
  },
  GenerateSalesEmail: {
    tableId: "",
    version: "",
    dataSourceType: "Connector",
    apis: {
      Run: {
        path: "/triggers/manual/run",
        method: "POST",
        parameters: [
          { name: "text", in: "body", required: true, type: "string" },
          { name: "text_1", in: "body", required: true, type: "string" },
          { name: "text_2", in: "body", required: true, type: "string" },
        ],
        responseInfo: {
          airesult: { type: "string" },
        },
      },
    },
  },
  SuggestAppointment: {
    tableId: "",
    version: "",
    dataSourceType: "Connector",
    apis: {
      Run: {
        path: "/triggers/manual/run",
        method: "POST",
        parameters: [
          { name: "text", in: "body", required: true, type: "string" },
          { name: "text_1", in: "body", required: true, type: "string" },
        ],
        responseInfo: {
          airesult: { type: "string" },
        },
      },
    },
  },
  GetOutlookEvents: {
    tableId: "",
    version: "",
    dataSourceType: "Connector",
    apis: {
      Run: {
        path: "/triggers/manual/run",
        method: "POST",
        parameters: [
          { name: "text", in: "body", required: true, type: "string" },
          { name: "text_1", in: "body", required: true, type: "string" },
        ],
        responseInfo: {
          events_json: { type: "string" },
        },
      },
    },
  },
  RefreshSummaries: {
    tableId: "",
    version: "",
    dataSourceType: "Connector",
    apis: {
      Run: {
        path: "/triggers/manual/run",
        method: "POST",
        parameters: [],
        responseInfo: {
          status: { type: "string" },
          message: { type: "string" },
        },
      },
    },
  },
  SendOutlookEmail: {
    tableId: "",
    version: "",
    dataSourceType: "Connector",
    apis: {
      Run: {
        path: "/triggers/manual/run",
        method: "POST",
        parameters: [
          { name: "text", in: "body", required: true, type: "string" },
          { name: "text_1", in: "body", required: true, type: "string" },
          { name: "text_2", in: "body", required: true, type: "string" },
        ],
        responseInfo: {
          result: { type: "string" },
        },
      },
    },
  },
  CreateOutlookEvent: {
    tableId: "",
    version: "",
    dataSourceType: "Connector",
    apis: {
      Run: {
        path: "/triggers/manual/run",
        method: "POST",
        parameters: [
          { name: "text", in: "body", required: true, type: "string" },
          { name: "text_1", in: "body", required: true, type: "string" },
          { name: "text_2", in: "body", required: true, type: "string" },
          { name: "text_3", in: "body", required: true, type: "string" },
          { name: "text_4", in: "body", required: true, type: "string" },
        ],
        responseInfo: {
          result: { type: "string" },
          eventId: { type: "string" },
        },
      },
    },
  },
  GenerateTerritoryNews: {
    tableId: "",
    version: "",
    dataSourceType: "Connector",
    apis: {
      Run: {
        path: "/triggers/manual/run",
        method: "POST",
        parameters: [
          { name: "text", in: "body", required: true, type: "string" },
        ],
        responseInfo: {
          airesult: { type: "string" },
        },
      },
    },
  },
};
