description: Blank Template
entityname: adx_webpage
id: a219f25b-1b0a-4f30-8d99-c4169887cecf
isdefault: false
name: Default studio template
type: 756150001
usewebsiteheaderandfooter: true
webtemplateid: 392db28d-0032-44cc-9591-980dd56a60e2
