description: 'The amount of time the IP address will have to wait if Authentication/LoginThrottling/MaxInvaildAttemptsFromIPAddress occur within Authentication/LoginThrottling/MaxAttemptsTimeLimitTimeSpan amount of time. Default: 00:10:00 (10 mins)'
id: 6a6a47e9-2143-4e66-bce8-77ae40d83020
name: Authentication/LoginThrottling/IpAddressTimeoutTimeSpan
value: 00:10:00
