description: 'The amount of time the Authentication/LoginThrottling/MaxInvaildAttemptsFromIPAddress are to be within before the IP address has to wait Authentication/LoginThrottling/IpAddressTimeoutTimeSpan. Default: 00:03:00 (3 mins)'
id: a6d5baed-8baf-4710-9324-d0729dd96cd0
name: Authentication/LoginThrottling/MaxAttemptsTimeLimitTimeSpan
value: 00:03:00
