annotationid: 680684bd-a5a0-4a45-b17c-3cc9b221dd61
enabletracking: false
excludefromsearch: false
filename: Logo-sm-64.png
hiddenfromsitemap: false
id: 1dccf0d1-f22b-46cc-94a2-ec429a23dff6
isdocument: true
mimetype: image/png
name: Logo-sm-64.png
objectid: 1dccf0d1-f22b-46cc-94a2-ec429a23dff6
objecttypecode: adx_webfile
parentpageid: 7dfee41a-698f-4cae-b790-948e94e4318b
partialurl: Logo-sm-64.png
publishingstateid: f19b400a-e073-431a-addd-49304e1ec833
