displayorder: 1
enablerating: false
enabletracking: false
excludefromsearch: false
feedbackpolicy: 756150005
hiddenfromsitemap: false
id: f5ff28ee-5e58-428c-bde7-f9713cbbae5e
isroot: false
name: Home
pagetemplateid: a219f25b-1b0a-4f30-8d99-c4169887cecf
partialurl: /
publishingstateid: c717ff14-a8c1-412c-accf-87e29e731d03
rootwebpageid: 66f96a25-2a12-409a-88f8-08706ae276f3
sharedpageconfiguration: false
title: Home
webpagelanguageid: c78a8b6f-871a-4ab7-b6d9-0a75635f27c2
