annotationid: 99100ea7-1fb9-497b-86f7-039a2eeab15b
displayorder: 10
enabletracking: false
excludefromsearch: true
filename: portalbasictheme.css
hiddenfromsitemap: false
id: dd78d956-8ac5-4909-8008-33dd7dcc1303
isdocument: true
mimetype: text/css
name: portalbasictheme.css
objectid: dd78d956-8ac5-4909-8008-33dd7dcc1303
objecttypecode: adx_webfile
parentpageid: 66f96a25-2a12-409a-88f8-08706ae276f3
partialurl: portalbasictheme.css
publishingstateid: c717ff14-a8c1-412c-accf-87e29e731d03
