// Auto-generated by pa app init + pa app add data-source
// Do NOT edit .power/schemas/appschemas/dataSourcesInfo.ts manually
import { dataSourcesInfo as generated } from "../../.power/schemas/appschemas/dataSourcesInfo"

// System tables not included in generated metadata
const systemTables = {
  systemusers: {
    tableId: "systemuser",
    version: "",
    primaryKey: "systemuserid",
    dataSourceType: "Dataverse",
    apis: {},
  },
}

export const dataSourcesInfo = {
  ...generated,
  ...systemTables,
}
