// Auto-generated by power-apps init + power-apps add-data-source
// Do NOT edit .power/schemas/appschemas/dataSourcesInfo.ts manually
import { dataSourcesInfo as generated } from "../../.power/schemas/appschemas/dataSourcesInfo"

// System tables not included in generated metadata
const systemTables = {
  systemusers: {
    tableId: "systemuser",
    version: "",
    primaryKey: "systemuserid",
    dataSourceType: "Dataverse",
    apis: {},
  },
}

// Flow connector — only present when VITE_FEATURE_APPROVAL_FLOW=true is configured
// Added via: npx power-apps add-flow --flow-id {FLOW_WORKFLOW_ID}
const flowConnectors = {} // populated after power-apps add-flow for the approval flow

export const dataSourcesInfo = {
  ...generated,
  ...systemTables,
  ...flowConnectors,
}
