// Auto-generated by pac code init + pac code add-data-source
// Do NOT edit .power/schemas/appschemas/dataSourcesInfo.ts manually
import { dataSourcesInfo as generated } from ".power/schemas/appschemas/dataSourcesInfo"

// System tables not added via pac code add-data-source
const systemTables = {
  systemusers: {
    tableId: "systemuser",
    version: "",
    primaryKey: "systemuserid",
    dataSourceType: "Dataverse",
    apis: {},
  },
}

// Flow connector — only present when VITE_FEATURE_APPROVAL_FLOW=true is configured
// Added via: pac code add-data-source -a logicflows -t {FLOW_WORKFLOW_ID}
const flowConnectors = {} // populated after pac code add-data-source for the approval flow

export const dataSourcesInfo = {
  ...generated,
  ...systemTables,
  ...flowConnectors,
}
