description: Sets whether or not the portal can redirect the user to the profile page after successful sign-in. By default, it is set to true.
id: d2f0c584-e674-4da4-94f9-be81c9845ae1
name: Authentication/Registration/ProfileRedirectEnabled
value: true
